# Toronto Dawn theme for Alacritty
# https://github.com/your-username/toronto.nvim

[colors.primary]
background = "#f9faff"
foreground = "#101010"
dim_foreground = "#56607b"

[colors.cursor]
text = "#f9faff"
cursor = "#101010"

[colors.vi_mode_cursor]
text = "#f9faff"
cursor = "#f28a3a"

[colors.selection]
text = "CellForeground"
background = "#d4dcff"

[colors.search.matches]
foreground = "#f9faff"
background = "#f28a3a"

[colors.search.focused_match]
foreground = "#f9faff"
background = "#379cff"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#101010"
background = "#f2f3fb"

[colors.normal]
black = "#f0f1ff"
red = "#ff568a"
green = "#2cbfc0"
yellow = "#f28a3a"
blue = "#2d8cff"
magenta = "#a95cff"
cyan = "#209fdf"
white = "#101010"

[colors.bright]
black = "#f0f1ff"
red = "#ff6a9b"
green = "#3ed3d4"
yellow = "#ffb25f"
blue = "#4b9dff"
magenta = "#bb78ff"
cyan = "#34b3f5"
white = "#404040"
